### PR TITLE
Should fetch all available environment variables

### PR DESCRIPTION
**Pull request by ilons**
# Bugfix
* Fetch all available deployment variables

### CODE REVIEW

**Comment by ilons** [comment]
Realised my fork were quite out of date, and now I cant seems to find where this would be done :S

**Comment by ilons** [comment]
So it looks like the client now lives in a different repository, and are quite refactored (and now handles multiple kinds of variabled), which would make my naive first approach unsuitable.

What should be done is to add pagination to the handling of responses here: https://github.com/DrFaust92/bitbucket-go-client/blob/main/api_pipelines.go#L1695

@DrFaust92 Is handling paginated responses in the client something you have been considering? For example, the deployment variables only return the first 10 (I haven't checked other variables)?

**Comment by DrFaust92** [comment]
Hi @ilons, client is autogenerated from Atlassian API Spec, if not supported there we can handwrite the logic and not use the client for this.

can you resolve conflicts so checks can run and ill merge?

**Comment by arun-sureshkumar** [comment]
@DrFaust92  - We are also experiencing the same issue "Provider produced inconsistent result after apply'? Any idea to fix this?

**Comment by arunsureshkumar** [comment]
We are also experiencing the same issue; any idea to fix this? "Provider produced inconsistent result after apply" @DrFaust92

**Comment by DrFaust92** [comment]
Thanks @ilons ive overridden this on the sdk level

**Comment by ilons** [comment]
@DrFaust92 Thank you for fixing this on the SDK level, much appreciated! Sorry that I didn't have the possibility to help out more!

**Comment by DrFaust92** [comment]
No worries, thanks for finding the issue.

**Pull request closed without merging**
